### ISSUE TITLE
Uh are you trying to packaging kresus ?

### ISSUE THREAD

**Issue by alexAubin** [artus40/cresus_ynh#1]
Hey there !

Just passing by, wondering if you are not in fact trying to recreate this existing package ? :sweat_smile: 
https://github.com/YunoHost-Apps/kresus_ynh

**Comment by artus40** [comment]
Hi !
Not at all, i'm just wrapping a modest django application I made to use with Yunohost :)

I didn't know this app though, and will definitely look into it, thanks !

**Comment by alexAubin** [comment]
Alright :wink: 

Don't hesitate to contact us on the various chatrooms if you need help with packaging or yunohost in general :P 

https://yunohost.org/#/chatrooms
